name = "utlz"
main = "worker.js"
compatibility_date = "2022-11-29"
node_compat=true

[[ d1_databases ]]
binding = "DB"
database_name = "utlz"
database_id = "3a5c572f-3da6-4d5b-b2d7-9b9acde5c628"

[[r2_buckets]]
binding = 'IMAGE_BUCKET'
bucket_name = 'utlz'
preview_bucket_name = 'utlz'

[triggers]
crons = ["*/30 * * * *"]

[site]
bucket = "./dist"